Add IL trimming support for DotNext.Metaprogramming
dotnet/dotNext pull request #219
Opened 2024-01-29 20:10 UTC by alexrp

Continuing from #218 (see https://github.com/dotnet/dotNext/pull/218#issuecomment-1915453664).

2024-01-30 21:57 UTC, sakno requested changes

2024-01-30 21:57 UTC, sakno commented on src/DotNext.Metaprogramming/Metaprogramming/MatchBuilder.cs
> +            [SuppressMessage("Trimming", "IL2026", Justification = "Public methods on MatchBuilder are annotated appropriately.")]
I think it's better to annotate CaseStatementBuilder with `RequiresUnreferencedCode` rather than suppression of the warning.

2024-01-30 22:08 UTC, alexrp commented on src/DotNext.Metaprogramming/Metaprogramming/MatchBuilder.cs
> +            [SuppressMessage("Trimming", "IL2026", Justification = "Public methods on MatchBuilder are annotated appropriately.")]
I wanted to do exactly that, but: https://github.com/dotnet/runtime/issues/90115

2024-01-30 22:20 UTC, alexrp commented on src/DotNext.Metaprogramming/Metaprogramming/MatchBuilder.cs
> +            [SuppressMessage("Trimming", "IL2026", Justification = "Public methods on MatchBuilder are annotated appropriately.")]
(Also just realized I should have made these `UnconditionalSuppressMessage`...)

2024-01-31 08:06 UTC, sakno commented on src/DotNext.Metaprogramming/Metaprogramming/MatchBuilder.cs
> +            [SuppressMessage("Trimming", "IL2026", Justification = "Public methods on MatchBuilder are annotated appropriately.")]
What a surprise from .net) Agree, let's turn it into unconditional flavor.

2024-02-01 07:11 UTC, alexrp commented
I just did some testing in a simple console app:

```csharp
static class Program
{
    [DynamicDependency(DynamicallyAccessedMemberTypes.All, typeof(MyClass<>))]
    static void Main()
    {
        Console.WriteLine(Type.GetType(Console.ReadLine()?.Trim() ?? string.Empty));
    }
}

class MyClass<T> // "MyClass`1" in Type.GetType()
{
}
```

Good news: It works! If you remove the attribute, publish with trimming, and run the program, it will fail to find the type. With the attribute, it will be there as expected. (Note: I'm getting the type name from user input to make 100% sure that it isn't just being preserved by the linker's dataflow analysis.)

So, going by this, it should be safe to sprinkle `[DynamicDependency]` where appropriate to get rid of some cases of `[RequiresUnreferecedCode]`.

2024-02-01 07:59 UTC, sakno commented
Does it mean that `[DynamicDependency(DynamicallyAccessedMemberTypes.All, typeof(MyClass<>))]` preserve all type instantiations of `MyClass<T>` found in the code?

2024-02-01 08:16 UTC, alexrp commented
> Does it mean that `[DynamicDependency(DynamicallyAccessedMemberTypes.All, typeof(MyClass<>))]` preserve all type instantiations of `MyClass<T>` found in the code?

I asked Michal on Discord and he said that it won't do that. But this should only matter for AOT. For JIT use cases, just having the uninstantiated class should be enough for any instantiation to work.

2024-02-15 09:03 UTC, alexrp commented
Just noting that I haven't forgotten about this. :slightly_smiling_face: I just have some other items on my to-do list that I need to check off before I get back to this.

2024-02-19 00:56 UTC, alexrp commented
Okay. I think I'm starting to come around to your position that it might just be too much work to do this accurately. I've run into multiple cases where I thought "oh, I'll just slap on `[DynamicDependency]` here", only to realize that it wouldn't actually cover *all* possible cases - e.g. places that deal with `Task`/`TaskAwaiter`-like types. It's increasingly looking like it's just going to be `[RequiresUnreferencedCode]` for 95% of the library. I suppose that's still better than nothing, since it at least bubbles the analysis warnings up to the user code and makes them actionable, but it's still not quite what I had hoped might be possible.

I'll keep poking at it for a bit, but it's not looking good for `[DynamicDependency]`.

2024-03-26 19:02 UTC, alexrp commented
@sakno I've mulled this over some more, and I think I might throw in the towel. Even for our use case of DotNext.Metaprogramming, we ended up deciding that writing a source generator made more sense for other reasons than trimming -- namely, startup performance, error detection, and debuggability -- so the primary motivation for this work is gone anyway. :pensive:

That said, if you like, I can split the addition of the DotNext.Trimming project into a separate PR as that ought to still be useful for more complete trimming analysis of the other DotNext libraries that are actually trimming-compatible. What do you think?

2024-07-12 13:44 UTC, CodingMadness commented
Any updates on this?

2025-05-21 23:01 UTC, closed without merging